/**
 * CREDITS — GDD Appendix F3.1, §10.9.2.
 *
 * F3.1 is short and one half of it is not optional: *"§10.9 puts CREDITS in the
 * menu; nothing specifies it. Departure Mono ships under the SIL OFL and its
 * licence **must** be reachable in-product."*
 *
 * **The licence is imported from the file that ships in the bundle**, with
 * Vite's `?raw`, rather than pasted in here. A copy would be a second text that
 * can drift from the one actually governing the font, and the failure mode of
 * that drift is a licence violation that no test can see. Importing the real
 * file also means the bundler proves it is present: delete the licence and the
 * build breaks, which is the correct relationship between an obligation and a
 * build.
 *
 * Everything else on this screen is deliberately thin. §22.7 caps the art
 * budget at nineteen sprites and none of them are a credits illustration, and
 * this project has one author.
 */

import licence from '../assets/fonts/DepartureMono-LICENSE.txt?raw'
import { Kw } from '../hud/Kw.tsx'

export function Credits() {
  return (
    <div className="credits">
      <h2 className="credits__title">CREDITS</h2>

      <dl className="credits__list">
        <dt>100,000,000 <Kw kind="devs">DEVELOPERS</Kw></dt>
        <dd>A STUDIO_OS production.</dd>

        <dt>DESIGN, CODE, SOUND</dt>
        <dd>Merciless Studio.</dd>

        <dt>TYPEFACE</dt>
        {/*
          The only text face in the product (ART_DIRECTION §3 rule 1 — no
          anti-aliased or vector fonts anywhere, including in this legal text,
          which is why the licence below is set in the font it licenses).
        */}
        <dd>Departure Mono 1.500 by Helena Zhang. SIL Open Font License 1.1.</dd>

        <dt>MUSIC &amp; EFFECTS</dt>
        {/* §20.7's stems and §20.5's bank are generated by scripts in this
            repository rather than licensed, so there is nobody else to credit
            and saying so is more useful than an empty row. */}
        <dd>Synthesised in-house. No sampled material.</dd>
      </dl>

      <h3 className="credits__licence-head">DEPARTURE MONO — SIL OPEN FONT LICENSE 1.1</h3>
      {/*
        `pre` and a scroll box: the OFL is a fixed-width legal document and
        re-wrapping it per viewport would set the same clause on a different
        grid on every device. §23.4's design box is 448 px tall, so this is the
        one place in the product that is allowed to scroll — and it scrolls
        inside itself, never the page.
      */}
      <pre className="credits__licence">{licence}</pre>
    </div>
  )
}
