#!/bin/bash
#
# 100,000,000 Developers — build a snapshot APK into .apk/ (git-ignored).
#
# A debug build with a timestamp for a version, for putting the current tree on
# a handset. Not a release build: it is signed with the debug key and it is not
# what goes to Play.
#

set -e
cd "$(dirname "$0")"

echo "============================================"
echo "  100M Developers — Snapshot APK Builder"
echo "============================================"
echo ""

SNAPSHOT_VERSION=$(date +"%Y%m%d-%H%M%S")
APK_NAME="m100devs-snapshot-${SNAPSHOT_VERSION}.apk"

echo "[1/4] Building web app..."
npm run build
echo ""

echo "[2/4] Syncing to Android..."
npx cap sync android
echo ""

# ─── Find the Android SDK ─────────────────────────────────────────────────────
#
# Gradle needs to be told where the SDK is, and the file that tells it —
# `android/local.properties` — is **gitignored**, correctly, because it holds a
# machine-specific absolute path. The consequence is that a fresh clone cannot
# build: Gradle stops with "SDK location not found", which reads like a broken
# checkout rather than a missing local file, and which cost this project a
# failed deploy that then blamed USB cables.
#
# So the path is discovered rather than required. Writing the file rather than
# exporting `ANDROID_HOME` is deliberate: on MinGW an exported path is a
# `/c/Users/...` string that the JVM does not understand, and `local.properties`
# takes the same forward-slash form on every platform. It is also what Android
# Studio itself writes, so the two cannot disagree.
ensure_android_sdk() {
    local props="android/local.properties"

    # Already pointed somewhere real? Leave it alone — a machine with two SDKs
    # has made a choice and this script is not the place to overrule it.
    if [[ -f "$props" ]] && grep -q '^sdk.dir=' "$props"; then
        local existing
        existing=$(grep '^sdk.dir=' "$props" | head -1 | cut -d= -f2- | tr -d '\r')
        if [[ -d "$existing" ]]; then
            echo "  SDK: ${existing} (from ${props})"
            return 0
        fi
        echo "  ${props} points at a path that does not exist — rediscovering."
    fi

    local candidates=()
    [[ -n "$ANDROID_HOME" ]]     && candidates+=("$ANDROID_HOME")
    [[ -n "$ANDROID_SDK_ROOT" ]] && candidates+=("$ANDROID_SDK_ROOT")
    [[ -n "$LOCALAPPDATA" ]]     && candidates+=("$LOCALAPPDATA/Android/Sdk")
    [[ -n "$USERPROFILE" ]]      && candidates+=("$USERPROFILE/AppData/Local/Android/Sdk")
    candidates+=(
        "$HOME/Android/Sdk"
        "$HOME/Library/Android/sdk"
        "/usr/lib/android-sdk"
        "/opt/android-sdk"
        "/usr/local/share/android-sdk"
        "C:/Android/Sdk"
    )

    # An SDK that cannot compile is not a find: `platforms` is what
    # `compileSdkVersion` resolves against.
    local sdk=""
    for c in "${candidates[@]}"; do
        if [[ -d "$c/platforms" && -d "$c/platform-tools" ]]; then sdk="$c"; break; fi
    done

    # Last resort: adb is on PATH, so the SDK is two directories above it.
    if [[ -z "$sdk" ]] && command -v adb &>/dev/null; then
        local guess
        guess=$(dirname "$(dirname "$(command -v adb)")")
        [[ -d "$guess/platforms" ]] && sdk="$guess"
    fi

    if [[ -z "$sdk" ]]; then
        echo "" >&2
        echo "Android SDK not found." >&2
        echo "" >&2
        echo "  Looked in: \$ANDROID_HOME, \$ANDROID_SDK_ROOT, and the usual per-OS locations." >&2
        echo "  Install it via Android Studio, or set ANDROID_HOME and re-run." >&2
        echo "" >&2
        return 1
    fi

    # Absolute, forward slashes, and a drive letter on Windows: `local.properties`
    # is a java.util.Properties file, where a backslash is an ESCAPE character —
    # `C:\Users\...` silently parses as `C:Users...` and Gradle then reports the
    # very same "SDK location not found" as if the file were missing entirely.
    if command -v cygpath &>/dev/null; then
        sdk=$(cygpath -m "$sdk")
    fi

    mkdir -p android
    {
        echo "## Generated by build-snapshot.sh — machine-specific, gitignored."
        echo "## Delete it to have the SDK rediscovered."
        echo "sdk.dir=${sdk}"
    } > "$props"
    echo "  SDK: ${sdk} (discovered, wrote ${props})"
}

echo "[3/4] Building Android APK..."
ensure_android_sdk
(cd android && chmod +x gradlew && ./gradlew assembleDebug)
echo ""

echo "[4/4] Copying APK..."
mkdir -p .apk
cp "android/app/build/outputs/apk/debug/app-debug.apk" ".apk/${APK_NAME}"
echo ""

if [[ "$OSTYPE" == "darwin"* ]]; then
    SIZE=$(stat -f%z ".apk/${APK_NAME}")
else
    SIZE=$(stat -c%s ".apk/${APK_NAME}")
fi

echo "============================================"
echo "  BUILD SUCCESSFUL!"
echo "============================================"
echo ""
echo "  APK: ${APK_NAME}"
echo "  Location: $(pwd)/.apk/${APK_NAME}"
echo "  Size: ${SIZE} bytes"
echo ""
echo "  Install it with ./deploy.sh --skip, or by hand:"
echo "    adb install -r .apk/${APK_NAME}"
echo "============================================"
